package general;

public class Edge {

}

enum EdgeType {
	// Border
	VOID, LEATHER, FLOWER, BOLT, BISQUIT, STOP,
	// Center,
	YELLOW_PIPES, GREEN_CIRCLE, BLUE_DIAMOND, BLUE_STAR, ORANGE_DIAMOND, YELLOW_STAR, PINK_DIAMOND, BLUE_CASTLE,
	PURPLE_STAR, YELLOW_CASTLE, YELLOW_CIRCLE, PINK_PIPES, PINK_CIRCLE, PINK_CASTLE, GREEN_RECTANGLE, ORANGE_PIPES,
	BLUE_RECTANGLE,

}