package general;

public enum EdgeType {
	NONE, VOID, BISQUIT, BLUE_CASTLE, BLUE_DIAMOND, BLUE_RECTANGLE, BLUE_STAR, BOLT, FLOWER, GREEN_CIRCLE,
	GREEN_RECTANGLE, LEATHER, ORANGE_DIAMOND, ORANGE_PIPES, PINK_CASTLE, PINK_CIRCLE, PINK_DIAMOND, PINK_PIPES,
	PURPLE_STAR, STOP, YELLOW_PIPES, YELLOW_CASTLE, YELLOW_CIRCLE, YELLOW_STAR,
}